### ISSUE TITLE
Transcribe transformation to a text document

### ISSUE THREAD

**Issue by jppianta83** [ESOM-2017-1/dragon-maze#12]

**Comment by andreantonitsch** [comment]
Requires all information encoded in UML.
Scenarios, a domain theory, a set of state variables, an ordered partition of that set.

Set of scenarios: 
	A set of sequence diagrams. 


Source model: 
The class corresponding to the component of interest is marked active.
All operations involved in the scenario are specified.
The the pre- and postconditions of the domain are applied to the operations.
Constraints of the form {state variable = value}.

Active class contributes an Attribute for each {state variable}.

Order of the {state variables Attributes} represents the prioritisation of the {state variables}.


Transformation:
A scenario specifies one particular path through the state machine component.
A state machine that only describes a particular path of the state machine component, that is, a scenario, is called a flat state machine.
1. apply domain theory
2. generate flat state machines
3. merge flat state machines
4. introduce hierarchy of merged state machines

4 ATL model Transformations correspond to the 4 steps, applied sequentially.
