### ISSUE TITLE
Question: ATL model transformation

### ISSUE THREAD

**Issue by andreantonitsch** [ESOM-2017-1/dragon-maze#15]
What is it?

**Comment by masmangan** [comment]
See ATL site:
[](http://www.eclipse.org/atl/
)
From their site:
"ATL (ATL Transformation Language) is a model transformation language and toolkit. In the field of Model-Driven Engineering (MDE), ATL provides ways to produce a set of target models from a set of source models."

See a brief tutorial at:
[](http://wiki.eclipse.org/ATL/Tutorials_-_Create_a_simple_ATL_transformation)
