### ISSUE TITLE
Install ATL

### ISSUE THREAD

**Issue by jppianta83** [ESOM-2017-1/dragon-maze#18]

**Comment by jppianta83** [comment]
During installation, encountered errors when writing data in the drive. The plugin appears to be installed in the end, but the example project doesn't load.

**Comment by jppianta83** [comment]
The error is probably in my drive, not in the plugin

**Comment by pbragaalves** [comment]
I guess this error is all about the insufficient space in the H drive. I think changing the workspace local should work.

**Comment by andreantonitsch** [comment]
ATL installation successful. ATL should be installed on a clean workspace in a partition with enough space and permissions.
